#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias s='startx'
alias n='nitrogen ~/sdb/wallpapers/'
alias nr='nitrogen --restore'
alias oops='sudo !!'
alias sn='sudo systemctl start snapd.service'
PS1='[\u@\h \W]\$ '
